wandb_version: 1

batch_size:
  desc: null
  value: 289
epochs:
  desc: null
  value: 95
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: 0
poly_lr:
  desc: null
  value: 0
dataset:
  desc: null
  value: CIFAR-10
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1699282900.643572
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.10.9
      5: 0.15.12
      6: 4.21.3
      8:
      - 1
      - 5
      13: linux-x86_64
